version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: php_lab5_nginx
    ports:
      - "80:80"       # Веб-приложение на порту 80
    volumes:
      - ./public:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - php_lab5_net

  php:
    image: php:8.1-fpm
    container_name: php_lab5_php
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./config:/var/www/config
      - ./storage:/var/www/storage
    networks:
      - php_lab5_net

  mysql:
    image: mysql:8.0
    container_name: php_lab5_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - php_lab5_net

  adminer:
    image: adminer
    container_name: php_lab5_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - php_lab5_net

volumes:
  db_data:

networks:
  php_lab5_net:
    driver: bridge
